### ISSUE TITLE
Build broken due to shutdown of codeaurora

### ISSUE THREAD

**Issue by volk-christian** [arduino/lmp-manifest#3]
Due to the shutdown of codeaurora at least the meta layer “meta-freescale” is broken. The links to the sources of the recipes don’t work anymore. None of the mentioned builds is possible in a plain workspace anymore. 

The links are already fixed in recent revisions of the “meta-freescale” layer. The manifest has to use an adapted revision.

**Comment by lmatusz** [comment]
Can you point What to do to use new links to repos? How to use an adopted revision?

**Comment by lmatusz** [comment]
I did changed layers directly and pointed some SRC URL to https://github.com/nxp-imx/... Hope for someone this will be helpfull.

**Comment by volk-christian** [comment]
The references to meta-freescale and meta-freescale-3rdparty are stored within lmp-bsp (https://github.com/arduino/lmp-manifest/blob/release/lmp-bsp.xml#L9). These revisions have to be updated to a newer one which is fitting to the rest of the build.

@lmatusz what did you change locally? The SRC_URIs inside the corresponding bitbake recipes?

**Comment by lmatusz** [comment]
> The references to meta-freescale and meta-freescale-3rdparty are stored within lmp-bsp (https://github.com/arduino/lmp-manifest/blob/release/lmp-bsp.xml#L9). These revisions have to be updated to a newer one which is fitting to the rest of the build.
> 
> @lmatusz what did you change locally? The SRC_URIs inside the corresponding bitbake recipes?

Yes inside Yocto layers to point to github repos.

**Comment by volk-christian** [comment]
@lmatusz did you do this by hand or did you setup a script which you could share?
An official fix would most probably require a factory manifest update which should be done by any maintainer of this project, being able to determine the dependencies of the included packages.

**Comment by lmatusz** [comment]
> @lmatusz did you do this by hand or did you setup a script which you could share?
> An official fix would most probably require a factory manifest update which should be done by any maintainer of this project, being able to determine the dependencies of the included packages.

I did it by hand since I am new to Yocto. All I did is to tried to compile the specific distro And when seen obstacles I have changed bb script reported in ERROR by hand.

**Comment by aentinger** [comment]
Hi @pennam :coffee: :wave: Could you possibly take a look at this?

**Comment by volk-christian** [comment]
After investigating a bit deeper, it figured out, that there is a newer foundies lmp release, which covers the changes in the mentioned layers regarding the move from codeaurora to github (https://github.com/foundriesio/lmp-manifest/releases/tag/89).

Unfortunately this release is incompatible with the meta-partner-arduino layer because of some changes in the distro and patches, which are applied by the meta-partner-arduino layer.

In order to get aligned again, the patches would have to be reviewed by the original author, which in most cases is @MaxPayne86...

**Comment by MaxPayne86** [comment]
New manifest should have fixed this, closing https://github.com/arduino/lmp-manifest/blob/183a09f7dd9df7cceaefe8b2a39ff6596b498f18/conf/local.conf#L96
